### ISSUE TITLE
/include/trace/define_trace.h:88:43: fatal error: ./mdss_pll_trace.h: No such file or directory

### ISSUE THREAD

**Issue by shabic** [nathanchance/bluecross#1]
### I have the following setup:

* Ubuntu 18.04 LTS
* android-msm-bluecross-4.9 commit 99672395c685f95b067f4dc381fa9e75f0b43d8a

### Trying to compile the driver but get the following error:
 
   CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  CHK     include/generated/bounds.h
  CHK     include/generated/timeconst.h
  CHK     include/generated/asm-offsets.h
  CALL    scripts/checksyscalls.sh
  CHK     scripts/mod/devicetable-offsets.h
  CHK     include/generated/compile.h
  CHK     kernel/config_data.h
  CC      drivers/clk/qcom/mdss/mdss-dsi-pll-10nm.o
In file included from drivers/clk/qcom/mdss/mdss_pll_trace.h:116:0,
                 from drivers/clk/qcom/mdss/mdss-dsi-pll-10nm.c:24:
./include/trace/define_trace.h:88:43: fatal error: ./mdss_pll_trace.h: No such file or directory
 #include TRACE_INCLUDE(TRACE_INCLUDE_FILE)
                                           ^
compilation terminated.
scripts/Makefile.build:339: recipe for target 'drivers/clk/qcom/mdss/mdss-dsi-pll-10nm.o' failed
make[4]: *** [drivers/clk/qcom/mdss/mdss-dsi-pll-10nm.o] Error 1
scripts/Makefile.build:653: recipe for target 'drivers/clk/qcom/mdss' failed
make[3]: *** [drivers/clk/qcom/mdss] Error 2
scripts/Makefile.build:653: recipe for target 'drivers/clk/qcom' failed
make[2]: *** [drivers/clk/qcom] Error 2
scripts/Makefile.build:653: recipe for target 'drivers/clk' failed
make[1]: *** [drivers/clk] Error 2
Makefile:1118: recipe for target 'drivers' failed
make: *** [drivers] Error 2

**Comment by nathanchance** [comment]
`make O=out` instead of just `make`.
