### ISSUE TITLE
Curious about trying this on a 3 XL

### ISSUE THREAD

**Issue by parkerlreed** [nathanchance/bluecross#2]
How is this in regards to hardware support? 

I see the PostmarketOS page mentions limited support but that was also quite a while ago. https://wiki.postmarketos.org/wiki/Google_Pixel_3_XL_(google-crosshatch)

I would love to test this out. Can this be built and booted with a standard cross-compiling setup?

EDIT: That is if this would even work for booting normal Linux. I guess that would be my end goal.

**Comment by artem** [comment]
This repo is just kernel sources for whatever Google ships with stock ROM + linux-stable merged on top of it

**Comment by parkerlreed** [comment]
Thanks.
